kind: Deployment
apiVersion: apps/v1
metadata:
  name: bazarr
  labels:
    app: bazarr
    part-of: bazarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bazarr
      part-of: bazarr
  template:
    metadata:
      labels:
        app: bazarr
        part-of: bazarr
    spec:
      containers:
      - name: bazarr
        image: ghcr.io/linuxserver/bazarr:1.1.0
        ports:
        - name: bazarr
          containerPort: 6767
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Europe/Paris"
        - name: UMASK
          value: "022"
        volumeMounts:
        - name: bazarr
          mountPath: /config
        - name: series
          mountPath: /series
        - name: animes
          mountPath: /animes
        - name: movies
          mountPath: /movies
        resources:
          limits:
            memory: 500Mi
          requests:
            memory: 450Mi
        readinessProbe:
          tcpSocket:
            port: bazarr
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: bazarr
          initialDelaySeconds: 15
          periodSeconds: 20
      volumes:
      - name: bazarr
        persistentVolumeClaim:
          claimName: bazarr
      - name: series
        persistentVolumeClaim:
          claimName: series
      - name: animes
        persistentVolumeClaim:
          claimName: animes
      - name: movies
        persistentVolumeClaim:
          claimName: movies
